/**
 * Workflow Type Constants
 * Defines all supported workflow types, states, and events in the system
 */

// Workflow Types
export const WORKFLOW_TYPES = {
  ALLOCATION: 'ALLOCATION',
  TRANSFER: 'TRANSFER',
  RETURN: 'RETURN',
  MAINTENANCE: 'MAINTENANCE',
  AUDIT: 'AUDIT',
  BOOKING: 'BOOKING'
}

// Asset Lifecycle States
export const ASSET_STATES = {
  AVAILABLE: 'AVAILABLE',
  RESERVED: 'RESERVED',
  ALLOCATED: 'ALLOCATED',
  UNDER_MAINTENANCE: 'UNDER_MAINTENANCE',
  LOST: 'LOST',
  RETIRED: 'RETIRED',
  DISPOSED: 'DISPOSED'
}

// Valid State Transitions
export const STATE_TRANSITIONS = {
  AVAILABLE: ['ALLOCATED', 'RESERVED', 'UNDER_MAINTENANCE', 'LOST', 'RETIRED', 'DISPOSED'],
  ALLOCATED: ['AVAILABLE', 'UNDER_MAINTENANCE', 'LOST'],
  RESERVED: ['AVAILABLE', 'ALLOCATED'],
  UNDER_MAINTENANCE: ['AVAILABLE', 'LOST'],
  LOST: [],
  RETIRED: [],
  DISPOSED: []
}

// Terminal States (no transitions out)
export const TERMINAL_STATES = ['LOST', 'RETIRED', 'DISPOSED']

// Approval States
export const APPROVAL_STATES = {
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  CANCELLED: 'CANCELLED'
}

// Booking States
export const BOOKING_STATES = {
  PENDING: 'PENDING',
  CONFIRMED: 'CONFIRMED',
  CANCELLED: 'CANCELLED',
  COMPLETED: 'COMPLETED',
  REJECTED: 'REJECTED'
}

// Valid Booking State Transitions
export const BOOKING_STATE_TRANSITIONS = {
  PENDING: ['CONFIRMED', 'REJECTED', 'CANCELLED'],
  CONFIRMED: ['COMPLETED', 'CANCELLED'],
  REJECTED: [],
  CANCELLED: [],
  COMPLETED: []
}

// Domain Events
export const DOMAIN_EVENTS = {
  // Asset Events
  ASSET_ALLOCATED: 'ASSET_ALLOCATED',
  ASSET_RETURNED: 'ASSET_RETURNED',
  ASSET_TRANSFERRED: 'ASSET_TRANSFERRED',
  ASSET_STATUS_CHANGED: 'ASSET_STATUS_CHANGED',
  
  // Transfer Events
  TRANSFER_REQUESTED: 'TRANSFER_REQUESTED',
  TRANSFER_APPROVED: 'TRANSFER_APPROVED',
  TRANSFER_REJECTED: 'TRANSFER_REJECTED',
  
  // Booking Events
  BOOKING_CREATED: 'BOOKING_CREATED',
  BOOKING_APPROVED: 'BOOKING_APPROVED',
  BOOKING_REJECTED: 'BOOKING_REJECTED',
  BOOKING_CANCELLED: 'BOOKING_CANCELLED',
  BOOKING_COMPLETED: 'BOOKING_COMPLETED',
  BOOKING_MODIFIED: 'BOOKING_MODIFIED',
  
  // Approval Events
  APPROVAL_CREATED: 'APPROVAL_CREATED',
  APPROVAL_COMPLETED: 'APPROVAL_COMPLETED',
  
  // Workflow Events
  WORKFLOW_STARTED: 'WORKFLOW_STARTED',
  WORKFLOW_COMPLETED: 'WORKFLOW_COMPLETED',
  WORKFLOW_FAILED: 'WORKFLOW_FAILED'
}

// Notification Types (used by NotificationService)
export const NOTIFICATION_TYPES = {
  ALLOCATION: 'ALLOCATION',
  TRANSFER: 'TRANSFER',
  APPROVAL: 'APPROVAL',
  MAINTENANCE: 'MAINTENANCE',
  AUDIT: 'AUDIT',
  BOOKING: 'BOOKING',
  ALERT: 'ALERT'
}

// Timeline Event Types (used by TimelineService)
export const TIMELINE_EVENTS = {
  ASSET_ALLOCATED: 'ASSET_ALLOCATED',
  ASSET_RETURNED: 'ASSET_RETURNED',
  ASSET_TRANSFERRED: 'ASSET_TRANSFERRED',
  MAINTENANCE_STARTED: 'MAINTENANCE_STARTED',
  MAINTENANCE_COMPLETED: 'MAINTENANCE_COMPLETED',
  AUDIT_COMPLETED: 'AUDIT_COMPLETED',
  BOOKING_CREATED: 'BOOKING_CREATED',
  BOOKING_APPROVED: 'BOOKING_APPROVED',
  BOOKING_REJECTED: 'BOOKING_REJECTED',
  BOOKING_CANCELLED: 'BOOKING_CANCELLED',
  BOOKING_COMPLETED: 'BOOKING_COMPLETED',
  BOOKING_MODIFIED: 'BOOKING_MODIFIED'
}

export default {
  WORKFLOW_TYPES,
  ASSET_STATES,
  STATE_TRANSITIONS,
  TERMINAL_STATES,
  APPROVAL_STATES,
  BOOKING_STATES,
  BOOKING_STATE_TRANSITIONS,
  DOMAIN_EVENTS,
  NOTIFICATION_TYPES,
  TIMELINE_EVENTS
}
